server:
  port: 8080

spring:
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/


  datasource:
    username: 'sam'
    password: 'password'
    url: jdbc:postgresql://localhost:5432/mobile-subscriber
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE


